// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZs6wh55_H52uodC8Zy7vMX-93sMrYoBM',
    appId: '1:452691989915:web:37388585ee796bbd283d3e',
    messagingSenderId: '452691989915',
    projectId: 'zsfoodorderapp',
    authDomain: 'zsfoodorderapp.firebaseapp.com',
    databaseURL: 'https://zsfoodorderapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'zsfoodorderapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5NCnJ2Hd-kez7ngOOnKGUjbDVt6Stq3g',
    appId: '1:452691989915:android:84aa5100bbb414e0283d3e',
    messagingSenderId: '452691989915',
    projectId: 'zsfoodorderapp',
    databaseURL: 'https://zsfoodorderapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'zsfoodorderapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRDo4uWeO6geaV6KgETNHzyh3jvJlbt9Q',
    appId: '1:452691989915:ios:914157e20e11608b283d3e',
    messagingSenderId: '452691989915',
    projectId: 'zsfoodorderapp',
    databaseURL: 'https://zsfoodorderapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'zsfoodorderapp.firebasestorage.app',
    iosBundleId: 'com.example.foodorder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRDo4uWeO6geaV6KgETNHzyh3jvJlbt9Q',
    appId: '1:452691989915:ios:914157e20e11608b283d3e',
    messagingSenderId: '452691989915',
    projectId: 'zsfoodorderapp',
    databaseURL: 'https://zsfoodorderapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'zsfoodorderapp.firebasestorage.app',
    iosBundleId: 'com.example.foodorder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZs6wh55_H52uodC8Zy7vMX-93sMrYoBM',
    appId: '1:452691989915:web:463cfd4c8a6eb410283d3e',
    messagingSenderId: '452691989915',
    projectId: 'zsfoodorderapp',
    authDomain: 'zsfoodorderapp.firebaseapp.com',
    databaseURL: 'https://zsfoodorderapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'zsfoodorderapp.firebasestorage.app',
  );
}
