platform :ios, '13.0'

use_frameworks!
use_modular_headers!


require_relative '../flutter_module/.ios/Flutter/podhelper' rescue nil
require_relative '../Flutter/Flutter/podhelper.rb' rescue nil

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
